// Based on https://github.com/tusharmath/node-config-ts/blob/master/src/createTypedefs.ts
const config = require('config');
const fs = require('fs');
const path = require('path');
const prettier = require('prettier');

const JsonToTS = require('json-to-ts');

const ts = prettier.format(
  [
    `// This file is auto-generated by tools/createDefineConfig.ts`,
    ...JsonToTS(config.get('Client'), {rootName: 'BtdClientConfig'}),
    `declare const __BTD_CONFIG: BtdClientConfig;`,
    `export const BtdConfig = __BTD_CONFIG as BtdClientConfig;`,
  ].join('\n'),
  {
    parser: 'typescript',
  }
);

fs.writeFileSync(path.resolve(process.cwd(), './src/defineConfig.ts'), ts);
